common:
  api_mode: false
  api_access_token: password
  default_url: []
  enable_insert: true
  insert_url: []
  prepend_insert_url: true
  exclude_remarks: ["(åˆ°æœŸ|å‰©ä½™æµé‡|æ—¶é—´|å®˜ç½‘|äº§å“)"]
  include_remarks: []
  enable_filter: false
  filter_script: ""
  default_external_config: "ACL4SSR_Online_Custom.ini"
  base_path: .
  clash_rule_base: base.tpl
  surge_rule_base: base.tpl
  surfboard_rule_base: base.tpl
  proxy_config: SYSTEM
  proxy_ruleset: SYSTEM
  proxy_subscription: NONE
  append_proxy_type: true

userinfo:
  stream_rule:
  - {match: "^å‰©ä½™æµé‡ï¼š(.*?)\\|æ€»æµé‡ï¼š(.*)$", replace: "total=$2&left=$1"}
  - {match: "^å‰©ä½™æµé‡ï¼š(.*?) (.*)$", replace: "total=$1&left=$2"}
  - {match: "^Bandwidth: (.*?)/(.*)$", replace: "used=$1&total=$2"}
  - {match: "^.*å‰©ä½™(.*?)(?:\\s*?)@(?:.*)$", replace: "total=$1"}
  - {match: "^.*?æµé‡:(.*?) å‰©:(?:.*)$", replace: "total=$1"}
  time_rule:
  - {match: "^è¿‡æœŸæ—¶é—´ï¼š(\\d+)-(\\d+)-(\\d+) (\\d+):(\\d+):(\\d+)$", replace: "$1:$2:$3:$4:$5:$6"}
  - {match: "^åˆ°æœŸæ—¶é—´(:|ï¼š)(\\d+)-(\\d+)-(\\d+)$", replace: "$1:$2:$3:0:0:0"}
  - {match: "^Smart Access expire: (\\d+)/(\\d+)/(\\d+)$", replace: "$1:$2:$3:0:0:0"}
  - {match: "^.*?æµé‡:(?:.*?) å‰©:(.*?)å¤©$", replace: "left=$1d"}

node_pref:
  udp_flag: true
  tcp_fast_open_flag: true
#  skip_cert_verify_flag: false
#  tls13_flag: false
  sort_flag: false
  sort_script: ""
  filter_deprecated_nodes: true
  append_sub_userinfo: true
  clash_use_new_field_name: true
  clash_proxies_style: flow
  rename_node:
  - {match: "(.*?)\\s-\\sShadowsocks.*$", replace: "$1"}
  - {match: "\\s*â­?\\(?\\[?((x|X)?(\\d+)(\\.?\\d+)?)((\\s?å€ç‡?)|(x|X))\\]?\\)?", replace: "[$1x]"}
  - {match: "^(.*?)\\sv2\\s?(.*)$", replace: "$1$2"}
  - {match: "\\[å€ç‡:(\\d+\\.?\\d*)\\]", replace: "[$1x]"}

managed_config:
  write_managed_config: true
  managed_config_prefix: "http://127.0.0.1:25500"
  config_update_interval: 86400
  config_update_strict: false
  quanx_device_id: ""
surge_external_proxy:
  surge_ssr_path: "" # /usr/bin/ssr-local
  resolve_hostname: true

emojis:
  add_emoji: true
  remove_old_emoji: true
  rules:
#  - {match: "(æµé‡|æ—¶é—´|åº”æ€¥)", emoji: "ğŸ³ï¸â€ğŸŒˆ"}
  - {match: "AC", emoji: "ğŸ‡¦ğŸ‡¨"}
  - {match: "(AR|é˜¿æ ¹å»·)", emoji: "ğŸ‡¦ğŸ‡·"}
  - {match: "(å¥¥åœ°åˆ©|ç»´ä¹Ÿçº³)", emoji: "ğŸ‡¦ğŸ‡¹"}
  - {match: "(AU|Australia|Sydney|æ¾³å¤§åˆ©äºš|æ‚‰å°¼)", emoji: "ğŸ‡¦ğŸ‡º"}
  - {match: "(BR|Brazil|å·´è¥¿|åœ£ä¿ç½—)", emoji: "ğŸ‡§ğŸ‡·"}
  - {match: "(FR|France|æ³•å›½|å·´é»)", emoji: "ğŸ‡«ğŸ‡·"}
  - {match: "(?i:UK|England|United.*?Kingdom|è‹±å›½|[^-]è‹±|ä¼¦æ•¦)", emoji: "ğŸ‡¬ğŸ‡§"}
  - {match: "(?i:HK|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|[^-]æ¸¯)", emoji: "ğŸ‡­ğŸ‡°"}
  - {match: "(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)", emoji: "ğŸ‡°ğŸ‡·"}
  - {match: "(JP|Japan|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|[^-]æ—¥)", emoji: "ğŸ‡¯ğŸ‡µ"}
  - {match: "(MO|Macao|æ¾³é—¨|CTM)", emoji: "ğŸ‡²ğŸ‡´"}
  - {match: "(SG|Singapore|æ–°åŠ å¡|ç‹®åŸ|[^-]æ–°)", emoji: "ğŸ‡¸ğŸ‡¬"}
  - {match: "(?i:US|America|United.*?States|ç¾å›½|[^-]ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥)", emoji: "ğŸ‡ºğŸ‡¸"}
  - {match: "(?i:TW|Taiwan|æ–°åŒ—|å½°åŒ–|CHT|å°æ¹¾|[^-]å°|HINET)", emoji: "ğŸ‡¨ğŸ‡³"}
  - {match: "(?i:CN|China|å›å›½|ä¸­å›½|æ±Ÿè‹|åŒ—äº¬|ä¸Šæµ·|å¹¿å·|æ·±åœ³|æ­å·|å¸¸å·|å¾å·|é’å²›|å®æ³¢|é•‡æ±Ÿ|æˆéƒ½|back)", emoji: "ğŸ‡¨ğŸ‡³"}

rulesets:
  enabled: true
  overwrite_original_rules: false
  update_ruleset_on_request: false
  rulesets:


proxy_groups:
  custom_proxy_group:

template:
  template_path: "templates"
  globals:
  - {key: clash.http_port, value: 7890}
  - {key: clash.socks_port, value: 7891}
  - {key: clash.allow_lan, value: true}
  - {key: clash.log_level, value: info}

aliases:
  - {uri: /v, target: /version}
  - {uri: /clash, target: "/sub?target=clash"}
  - {uri: /clashr, target: "/sub?target=clashr"}
  - {uri: /surge, target: "/sub?target=surge"}
  - {uri: /quan, target: "/sub?target=quan"}
  - {uri: /quanx, target: "/sub?target=quanx"}
  - {uri: /mellow, target: "/sub?target=mellow"}
  - {uri: /surfboard, target: "/sub?target=surfboard"}
  - {uri: /loon, target: "/sub?target=loon"}
  - {uri: /ss, target: "/sub?target=ss"}
  - {uri: /ssd, target: "/sub?target=ssd"}
  - {uri: /sssub, target: "/sub?target=sssub"}
  - {uri: /ssr, target: "/sub?target=ssr"}
  - {uri: /v2ray, target: "/sub?target=v2ray"}
  - {uri: /trojan, target: "/sub?target=trojan"}

server:
  listen: 0.0.0.0
  port: 25500
  serve_file_root: ""

advanced:
  log_level: info
  print_debug_info: false
  max_pending_connections: 10240
  max_concurrent_threads: 2
  max_allowed_rulesets: 0
  max_allowed_rules: 0
  max_allowed_download_size: 0
  enable_cache: false
  cache_subscription: 60
  cache_config: 300
  cache_ruleset: 21600
  async_fetch_ruleset: false
  skip_failed_links: false
